// GENERATED by scripts/gen-paddle-config.mjs — do not edit by hand.
// Run `npm run paddle:config` to regenerate from .env.
//
// This is a Paddle *client-side* token. It is public by design: every visitor's
// browser receives it. The server-side API key must never appear here.
window.__PADDLE_CONFIG__ = {
  "environment": "production",
  "token": "live_1897f5fe478ea9c13f5666280c5"
};
